feat: auto tracking function
cloudinary/cloudinary-video-analytics pull request #1
Opened 2023-08-16 08:37 UTC by jakub-roch

2023-08-17 08:37 UTC, ehab-cl approved these changes
LGTM 👍

2023-08-22 12:08 UTC, jakub-roch commented on src/utils/parseVideoUrl.js
> +const CLOUDINARY_URL_BASE_REGEX = /^\/?(?<cloudName>[^\/]+)\/(?<assetType>video)\/(?<deliveryType>upload|fetch)\/(?<rest>.*)$/;
no more relevant

2023-08-22 19:53 UTC, ehab-cl approved these changes
LGTM 💪

2023-08-22 19:53 UTC, ehab-cl commented on src/data-collectors/automatic-data-collector.js
> +      videoWatchSessionId: data.videoWatchSessionId, // new property
```suggestion
      videoWatchSessionId: data.videoWatchSessionId, 
```

2023-08-23 08:04 UTC, kjarmicki-cloudinary requested changes

2023-08-23 08:04 UTC, kjarmicki-cloudinary commented on src/data-collectors/automatic-data-collector.js
> +      videoWatchSessionId: data.videoWatchSessionId,
nope, `viewId` 🙂
we don't have a notion of a `session` is our language, a single interaction with a video (be it impression or watching) is called a `view`.

my advice would be to get rid of the session word from the code too and replace things like `getVideoSessionId` with `getViewId`.

---

also, this is cosmetic, but I noticed you're using plain uuidv4() to generate this ID, so they will look something like `3c8f2860-5f1b-4487-9a26-b59db967755a` - note that this will be an identifier available through the public API and we generally don't expose IDs with hyphens, so for the sake of keeping the look and feel similar, consider removing the hyphens

2023-08-24 05:30 UTC, jakub-roch commented on src/data-collectors/automatic-data-collector.js
> +      videoWatchSessionId: data.videoWatchSessionId,
changed to viewId 👍

2023-08-24 06:04 UTC, merged